import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ISS(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/ISS-compressed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={10} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001.geometry}
          material={materials.ISS_02_dull}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_1.geometry}
          material={materials.ISS_01_dull}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_2.geometry}
          material={materials.ISS_AO_05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_3.geometry}
          material={materials.ISS_03_dull}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_4.geometry}
          material={materials.ecostress}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_5.geometry}
          material={materials["plastic black"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_6.geometry}
          material={materials.ecostressWhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_7.geometry}
          material={materials["ISS_03_dull.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_8.geometry}
          material={materials["ecostress metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_9.geometry}
          material={materials.ecostress_dexter}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_10.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_11.geometry}
          material={materials.base_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_12.geometry}
          material={materials["ISS_01_dull.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_13.geometry}
          material={materials["ISS_03_dull.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_14.geometry}
          material={materials.shiny_panel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_15.geometry}
          material={materials.ISS_01_shiny_n}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_16.geometry}
          material={materials.ISS_AO_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_17.geometry}
          material={materials.ISS_AO_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_18.geometry}
          material={materials.ISS_AO_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_19.geometry}
          material={materials["ISS_01_dark *"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_20.geometry}
          material={materials.foil_silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_21.geometry}
          material={materials.ISS_03_shiny_n}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_22.geometry}
          material={materials.ISS_AO_04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_23.geometry}
          material={materials.ISS_AO_06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_24.geometry}
          material={materials["ISS_02_dark *"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_25.geometry}
          material={materials.ISS_04_dull}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_26.geometry}
          material={materials.ISS_AO_07}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_27.geometry}
          material={materials["olive *"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mss_mbs001_28.geometry}
          material={materials.ISS_AO_08}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ISS-compressed.glb");